sudo: required
services:
  - docker

before_install:
  - docker build -t ngingnpminstall -f Dockerfile.dev .
script:
  - docker run ngingnpminstall npm run test -- --coverage
#deploy:
# https://docs.travis-ci.com/user/deployment/azure-web-apps/
#provider: azure_web_apps
#username: $username
#password: $password
#site: '$site
# slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
#on:
 # branch: master
